sudo: required
language: node_js
node_js:
- node
script:
- npm run-script test-travis
services:
- docker
after_script: cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js
after_success:
- docker build -t bondanthony/nodetester .
- docker run -d --name=nodetester -p 80:3000 bondanthony/nodetester
- docker ps -a
- wget http://localhost/api/server1 && wget http://localhost/api/server2 || exit 1
- if [ "$TRAVIS_BRANCH" == "master" ]; then docker login -u="$DOCKERU" -p="$DOCKERP"; docker
  push $DOCKERU/nodetester; fi
env:
  global:
  - secure: GoTged3RLE8xq/nKZ89+Rp4W3ZO2BkuT1Quxs9956x/CAfX47J2q/H4xwss0ptsQhyJCbNdmoiCqze/qM+u7b5/QD9utlyDXVY7+XtlaS9sGKpn0BzSYC5P5GUGEE2IcdRFvBX98AJl665/z2tMt5mNBMEb5z25mxlNEXqLOKWguJ0EjWL6Qf8YsDCQYGI2b8X80UQmeXcQnWSt/FtxEils90PxuXEvZDF/eavtA3RqOHJuJHWcG5YIrfhZp9IC/U2Lzw+1m/Kfv6psJHSd1o6YvAkXKsBpeZkti++MrMf3dPuUNE5dLYuZTQR/NrIGDhohbahPw50oWeBxGBKS2RcAyI79JgQ30RVTYYi4ZPA7y4NgplqytyK/B/jCO3V81nG54GeHzmCvtGfIKCLbrZ/Gqgk/09IosYQntkjOzKUvVsa7Krd+EtZugRMiuOxGjQyr2aO9qHvSxfch08UCMlLVVn8MWKpkrMtysDbZnvYlUmr2rQf8CzlpBkpt52YvtcVA9X6m3ggo1jDqDPNI4qPccfhyX8sMfi+m7drHlA3ZTmRRv3VU8nSnvDvOxwcW12v/0EouSISsDQqDptTi7Ll5Vl7L3n62Jo3U86k3mOV1wwwuAMMEMWR4DjEhAM704p7/XA88wsQxzZhHyP6YEPudDvizYfZvuG9/szQn4Q24=
  - secure: J5nZHup3t9a3dztFFuNPbnpr6y1BYH0oRdjlP2QYwmukuOmlejwnlRtbadPhiarQiea2e9Po3AtVRxH9FqpYD9vjFS5P4IJfvuAw0nfa6d9jgMJk3eMXsWJBciFwYCJ6MsRWK962R2nzuVFhnB0pYgciez9hPLaK2C7roqQWxAq6w5d29+GiEVj9lgyh9Q5/N7DCxeD6Dh4FIw79jn83IMgN1cxtAKKDLtp/nfQ6rjQkHVwOdzC01odd+YZB1qL5gIrJxIj6scmFvCcaYLKD1alXE5XE9i2URZuwmK8uKv4xyyGznqaILdtjgWecpTntON1kCC7DvqjmwflDhY6HlNQf/eTgs44vjpAxNt3MLC8jhonPdtUllno9KMoF4abwqjZogaUQ5UJfD8Kx4+Q6WvNP4HTiqqI85Qhyy+2z4bs2qLTAMF7ipsp8mz98jnGZjg5J4/H52IdlAekiA+3iemWTg2PC9cjscH4CA20xHZlmGgbRynFhmQIcLP+flR999Ejaij29AIo5b94zCUW/2SR8vy/ARdI/t2RHPFNYxkqMBZsDJg1Mkm5CuPWUmsgLt0LNvrSE1NWx/5e3+0yA6ptdivSJwgYv8BAOHwXmEs9aM0tnazgAFoSvCOfkYd3kJqik1HrIl4yC1AcnYf0VLcAjsNFL+F1lYP5VmQjtopE=
