sudo: required
language: mode_js
node_js:
  - node
script:
  - npm test
services:
  - docker
before_install: 
  - docker build -t bondanthony/nodetester
  - docker run -d --name=nodetester -p 80:3000 bondanthony/nodetester
  - docker ps -a